package com.example.junckcleaner.annotations;

public @interface MyAnnotations {
    String PREFERENCES = "PREFERENCES";

    String JUNK_LAST_CLEANED_TIME = "JUNK_LAST_CLEANED_TIME";

    String INSTALLATION = "INSTALLATION";
    String APP_ICON = "APP_ICON";
    String APP_NAME = "APP_NAME";
    String APP_VERSION = "APP_VERSION";
    String BOOST = "BOOST";
    String BOOST_LAST_CLEANED_TIME = "BOOST_LAST_CLEANED_TIME";
    String COOL_LAST_CLEANED_TIME = "COOL_LAST_CLEANED_TIME";
    String COOLER = "COOLER";
    String POWER_SAVED_LAST_TIME = "POWER_SAVED_LAST_TIME";


    String table_apps = "table_apps";
    String table_intruders = "table_intruders";
    String new_alert_table = "new_alert_table";

    String DELETE_FROM_table_apps = "DELETE FROM table_apps";
    String SELECT_ALL_FROM_table_apps = "SELECT * FROM table_apps";

    String APPS_SET = "APPS_SET";
    String DND_PERMISSION = "DND_PERMISSION";
    String ANTIVIRUS = "ANTIVIRUS";
    String DATA_TYPE = "DATA_TYPE";
    String IMAGES = "IMAGES";
    String VIDEOS = "VIDEOS";
    String AUDIOS = "AUDIOS";
    String DOCUMENTS = "DOCUMENTS";


    String TAKE_SELFIE = "TAKE_SELFIE";
    String FINGER_PRINT = "FINGER_PRINT";
    String NEW_ALERT = "NEW_ALERT";
    String VIB_FEEDBACK = "VIB_FEEDBACK";
    String SECURITY_EMAIL = "SECURITY_EMAIL";
    String AUTOMATICALLY_LOCK = "AUTOMATICALLY_LOCK";

    String AFTER_SCREEN_OFF = "AFTER_SCREEN_OFF";
    String IMMEDIATELY = "IMMEDIATELY";
    String SECONDS_30 = "SECONDS_30";
    String MINUTE_1 = "MINUTE_1";
    String MINUTES_5 = "MINUTES_5";
    String MINUTES_10 = "MINUTES_10";

    String WRONG_ATTEMPTS = "WRONG_ATTEMPTS";
    String TIMES_3 = "TIMES_3";
    String TIMES_4 = "TIMES_4";
    String TIMES_5 = "TIMES_5";
    String TIMES_10 = "TIMES_10";
    String TIMES_15 = "TIMES_15";

    String IS_LOCKED = "IS_LOCKED";
    String PATTERN = "PATTERN";
    String SECURITY_Q = "SECURITY_Q";
    String SECURITY_A = "SECURITY_A";
    String PATTERN_ENABLED = "PATTERN_ENABLED";
    String PIN_IS_CREATED = "PIN_IS_CREATED";
    String PIN = "PIN";
    String EXTRA_WHAT_TO_DO = "EXTRA_WHAT_TO_DO";
    String CHANGE_PIN = "CHANGE_PIN";
    String CREATE_PIN = "CREATE_PIN";
    String ENTER_PIN = "ENTER_PIN";
    String CHANGE_PATTERN = "CHANGE_PATTERN";
    String CREATE_PATTERN = "CREATE_PATTERN";
    String DRAW_PATTERN = "DRAW_PATTERN";
    String FORGOT_PIN = "FORGOT_PIN";
    String FORGOT_PATTERN = "FORGOT_PATTERN";
    String INTRUDER_APP = "INTRUDER_APP";
    String INTRUDER_PATH = "INTRUDER_PATH";
    String INTRUDER_DATE = "INTRUDER_DATE";
    String INTRUDER_TIME = "INTRUDER_TIME";
    String INTRUDER_ATTEMPTS = "INTRUDER_ATTEMPTS";
    String CURRENT_APP = "CURRENT_APP";
    String PREVIOUS_APP = "PREVIOUS_APP";
    String OTP = "OTP";
    String ANTIVIRUS_APPS = "ANTIVIRUS_APPS";
    String DANGEROUS_APP = "DANGEROUS_APP";
    String SCAN_TYPE = "SCAN_TYPE";
    String ALL_SCAN = "ALL_SCAN";
    String NOTIFICATION_MANAGEMENT = "NOTIFICATION_MANAGEMENT";
    String NOTY_APPS = "NOTY_APPS";
    String NOTIFICATIONS = "NOTIFICATIONS";
    String NOTIFICATION_FRAGMENT = "NOTIFICATION_FRAGMENT";
    String SMART_CHARGE_ENABLED = "SMART_CHARGE_ENABLED";
    String WIFI_SWITCH = "WIFI_SWITCH";
    String BRIGHTNESS_SWITCH = "BRIGHTNESS_SWITCH";
    String BLUETOOTH_SWITCH = "BLUETOOTH_SWITCH";
    String SYNCHRONIZED_SWITCH = "SYNCHRONIZED_SWITCH";
    String CHARGING_FINISHED_SWITCH = "CHARGING_FINISHED_SWITCH";
    String EVERY_DAY = "EVERY_DAY";
    String NEVER_REMIND = "NEVER_REMIND";
    String EVERY_7_DAY = "EVERY_7_DAY";
    String EVERY_3_DAY = "EVERY_3_DAY";
    String JUNK_REMINDER_FREQUENCY = "JUNK_REMINDER_FREQUENCY";
    String PHONE_BOOST_REMINDER = "PHONE_BOOST_REMINDER";
    String CPU_COOLER_REMINDER = "CPU_COOLER_REMINDER";
    String BATTERY_SAVER = "BATTERY_SAVER";
    String APP_INSTALL = "APP_INSTALL";
    String APP_UN_INSTALL = "APP_UN_INSTALL";
    String REAL_TIME_PROTECTION = "REAL_TIME_PROTECTION";
    String ID = "ID";
    String NOTIFICATIONS_JUNK_NEXT_TIME = "NOTIFICATIONS_JUNK_LAST_TIME";
    String NOTIFICATIONS_PHONE_BOOST_NEXT_TIME = "NOTIFICATIONS_PHONE_BOOST_NEXT_TIME";
    String NOTIFICATIONS_CPU_COOLER_NEXT_TIME = "NOTIFICATIONS_CPU_COOLER_NEXT_TIME";
    String NOTIFICATIONS_BATTERY_SAVER_NEXT_TIME = "NOTIFICATIONS_BATTERY_SAVER_NEXT_TIME";
    String DND_SWITCH = "DND_SWITCH";
    String DND_START_TIME = "DND_START_TIME";
    String DND_END_TIME = "DND_END_TIME";
    String PROTECTED_APPS = "PROTECTED_APPS";
    String IGNORE_APPS = "IGNORE_APPS";
    String PLAY_ANIMATION = "PLAY_ANIMATION";
    String ALL_APPS = "ALL_APPS";
    String IN_APP = "IN_APP";
    String GAME_BOOSTER_APPS = "GAME_BOOSTER_APPS";
    String USER_APPS = "USER_APPS";
    String START_LOCKER_SERVICE = "START_LOCKER_SERVICE";
    String START_SERVICE_REMINDER = "START_SERVICE_REMINDER";
    String START_SMART_SERVICE = "START_SMART_SERVICE";
    String PATTERN_IS_CREATED = "PATTERN_IS_CREATED";
}
